repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
        language: system
      - id: check-yaml
        language: system
      - id: end-of-file-fixer
        language: system
      - id: trailing-whitespace
        language: system
      - id: check-added-large-files
        language: system
        args: ["--maxkb=1000"]

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language: system

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        language: system

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        language: system

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.408
    hooks:
      - id: pyright
        language: system
