# Find books published before 1960.

PREFIX ex: <http://example.org/library/>

SELECT ?title ?year
WHERE {
    ?book  a             ex:Book ;
           ex:title      ?title ;
           ex:published  ?year .
    FILTER (?year < 1960)
}
ORDER BY ?year
